spool solution12

set echo on
set feedback on
set linesize 100
set pagesize 200

SELECT USER_INDEXES.TABLE_NAME, COUNT(*) AS INDEXES
FROM USER_INDEXES
INNER JOIN USER_TABLES ON USER_TABLES.TABLE_NAME = USER_INDEXES.TABLE_NAME
GROUP BY USER_INDEXES.TABLE_NAME
ORDER BY INDEXES DESC;

spool off