spool dbcount

set echo on
set feedback on
set linesize 150
set pagesize 300

SELECT (SELECT COUNT(*) FROM ORDER_DETAIL ) ORDER_DETAIL,
       (SELECT COUNT(*) FROM ORDERS ) ORDERS,
       (SELECT COUNT(*) FROM PRODUCT ) PRODUCT,
       (SELECT COUNT(*) FROM SUPPLIER ) SUPPLIER,
       (SELECT COUNT(*) FROM CATEGORY ) CATEGORY,
       (SELECT COUNT(*) FROM CUSTOMER ) CUSTOMER,
       (SELECT COUNT(*) FROM EMPLOYEE ) EMPLOYEE,
       (SELECT COUNT(*) FROM SHIPPER ) SHIPPER
FROM DUAL;

spool off
