SET ECHO OFF
SET PAGESIZE 100
SET LINESIZE 70
SET FEEDBACK OFF
TTITLE "USER OBJECTS"
COLUMN object_name FORMAT A30 HEADING "OBJECT NAME"
COLUMN object_type FORMAT A15 HEADING "OBJECT TYPE"
COLUMN created_on FORMAT A20 HEADING "CREATED ON"
select object_name, object_type, TO_CHAR( created, 'DD Month YYYY') created_on from user_objects;
PROMPT
TTITLE OFF;
COLUMN object_name CLEAR
COLUMN object_type CLEAR
COLUMN created_on CLEAR
SET FEEDBACK ON
SET ECHO ON

