SET ECHO OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET LINESIZE 90
SET PAGESIZE 100
ACCEPT TNAME CHAR PROMPT 'TABLE>'
TTITLE "ATTRIBUTES"
COLUMN table_name FORMAT A15 HEADING "TABLE NAME"
COLUMN column_name FORMAT A15 HEADING "ATTRIBUTE NAME"
COLUMN data_type FORMAT A8 HEADING "TYPE"
SELECT table_name,
       column_name,
       data_type,
       data_length "LENGTH",
       data_precision "PRECISION",
       data_scale "SCALE"
FROM   user_tab_columns
WHERE  table_name = upper('&TNAME');
TTITLE "CONSTRAINTS"
SET LINESIZE 90
COLUMN table_name FORMAT A15 HEADING "TABLE NAME"
COLUMN constraint_name FORMAT A15 HEADING "CONSTRAINT"
COLUMN search_condition FORMAT A30 HEADING "CONDITION"
SELECT table_name,
       constraint_name,
       decode(constraint_type, 'P', 'PRIMARY KEY',
				'U', 'CANDIDATE KEY',
                                'R', 'FOREIGN KEY',
                                'C', 'DOMAIN:' )  TYPE, 
       search_condition
FROM   user_constraints
WHERE  table_name = upper('&TNAME');
TTITLE "COLUMNS INVOLVED IN CONSTRAINTS"
SET LINESIZE 90
COLUMN table_name FORMAT A15 HEADING "TABLE NAME"
COLUMN constraint_name FORMAT A15 HEADING "CONSTRAINT"
COLUMN column_name FORMAT A30 HEADING "COLUMN"
COLUMN position FORMAT 99999999 HEADING "POSITION"
SELECT table_name,
       constraint_name,
       column_name,
       position
FROM   user_cons_columns
WHERE  table_name = upper('&TNAME');
TTITLE "REFERENCES"
SET LINESIZE 90
BREAK ON CONSTRAINT_NAME
COLUMN TABLE_NAME FORMAT A10 HEADING "TABLE"
COLUMN COLUMN_NAME FORMAT A10 HEADING "COLUMN"
COLUMN CONSTRAINT_NAME FORMAT A15 HEADING "CONSTRAINT"
COLUMN R_CONSTRAINT_NAME FORMAT A22 HEADING "REFERENCED CONSTRAINT"
COLUMN REFERENCES FORMAT A10 HEADING "          "
SELECT USER_CONSTRAINTS.CONSTRAINT_NAME CONSTRAINT_NAME,
       UCC1.TABLE_NAME TABLE_NAME, 
       UCC1.COLUMN_NAME COLUMN_NAME,
       '--------->' REFERENCES,
       UCC2.TABLE_NAME TABLE_NAME,
       UCC2.COLUMN_NAME COLUMN_NAME
FROM   USER_CONSTRAINTS, 
       USER_CONS_COLUMNS UCC1,
       USER_CONS_COLUMNS UCC2
WHERE  USER_CONSTRAINTS.CONSTRAINT_NAME = UCC1.CONSTRAINT_NAME AND
       USER_CONSTRAINTS.R_CONSTRAINT_NAME = UCC2.CONSTRAINT_NAME AND
       UCC1.POSITION = UCC2.POSITION AND
       CONSTRAINT_TYPE = 'R' AND
       UCC1.TABLE_NAME= upper('&TNAME');
PROMPT
TTITLE OFF
SET FEEDBACK ON
SET VERIFY ON
SET ECHO ON
